-- Generated by Copilot
-- Create tables with IDENTITY columns for auto-incrementing IDs

-- Create Supplier table
CREATE TABLE Supplier (
    supplierId INT IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT
);

-- Create Branch table
CREATE TABLE Branch (
    branchId INT IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT
);

-- Create Headquarters table
CREATE TABLE Headquarters (
    headquartersId INT IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT
);

-- Create Order table (using Order_ since ORDER is a reserved word)
CREATE TABLE Order_ (
    orderId INT IDENTITY(1,1) PRIMARY KEY,
    orderDate DATE NOT NULL,
    headquartersId INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    FOREIGN KEY (headquartersId) REFERENCES Headquarters(headquartersId)
);

-- Create Product table
CREATE TABLE Product (
    productId INT IDENTITY(1,1) PRIMARY KEY,
    supplierId INT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    FOREIGN KEY (supplierId) REFERENCES Supplier(supplierId)
);

-- Create OrderDetail table
CREATE TABLE OrderDetail (
    orderDetailId INT IDENTITY(1,1) PRIMARY KEY,
    productId INT NOT NULL,
    orderId INT NOT NULL,
    productQuantity INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    FOREIGN KEY (productId) REFERENCES Product(productId),
    FOREIGN KEY (orderId) REFERENCES Order_(orderId)
);

-- Create Delivery table
CREATE TABLE Delivery (
    deliveryId INT IDENTITY(1,1) PRIMARY KEY,
    deliveryDate DATE NOT NULL,
    supplierId INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    FOREIGN KEY (supplierId) REFERENCES Supplier(supplierId)
);

-- Create OrderDetailDelivery junction table
CREATE TABLE OrderDetailDelivery (
    deliveryId INT,
    orderId INT,
    orderDetailId INT,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    PRIMARY KEY (deliveryId, orderId, orderDetailId),
    FOREIGN KEY (deliveryId) REFERENCES Delivery(deliveryId),
    FOREIGN KEY (orderId) REFERENCES Order_(orderId),
    FOREIGN KEY (orderDetailId) REFERENCES OrderDetail(orderDetailId)
);

-- Create indexes for performance
CREATE INDEX IX_Order_HeadquartersId ON Order_(headquartersId);
CREATE INDEX IX_Product_SupplierId ON Product(supplierId);
CREATE INDEX IX_OrderDetail_ProductId ON OrderDetail(productId);
CREATE INDEX IX_OrderDetail_OrderId ON OrderDetail(orderId);
CREATE INDEX IX_Delivery_SupplierId ON Delivery(supplierId);
CREATE INDEX IX_OrderDetailDelivery_DeliveryId ON OrderDetailDelivery(deliveryId);
CREATE INDEX IX_OrderDetailDelivery_OrderId ON OrderDetailDelivery(orderId);
CREATE INDEX IX_OrderDetailDelivery_OrderDetailId ON OrderDetailDelivery(orderDetailId);
